# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

target "HydMMTSLive" do

pod 'AFNetworking'
pod 'Canvas', '~> 0.1'
pod 'FlatUIKit'

end

target "HydMMTSLiveTests" do

end

